### ISSUE TITLE
Placement stays in `Unbound` phase if `namespaceSelector` is nil

### ISSUE THREAD

**Issue by astefanutti** [kcp-dev/contrib-tmc#86]
### Describe the bug

When creating a Placement, without specifying `namespaceSelector`, it stays in `Unbound` phase, while the documentation states the field is optional, and all namespaces are matched by default.

### Steps To Reproduce

```
cat <<EOF | kubectl apply -f -
apiVersion: scheduling.kcp.dev/v1alpha1
kind: Placement
metadata:
  name: default
spec:
  locationWorkspace: root:location:workspace
  locationResource:
    group: workload.kcp.dev
    resource: synctargets
    version: v1alpha1
EOF
```

### Expected Behaviour

The Placement should be bound, even if `namespaceSelector` is nil.

### Additional Context

It works by adding `namespaceSelector: {}` to the Placement spec.
